#!/bin/bash
cd LIB
gcc -c -fPIC *.c
gcc -shared -o liboperations.so *.o
echo "objdump is ------> "
objdump -T liboperations.so
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${PWD}
echo "path is ------>"
echo $LD_LIBRARY_PATH
cd ../
gcc main.c -o Calc -l operations -L ./LIB -I ./INCLUDE
echo " "
./Calc

